### ISSUE TITLE
使用docker 私有化部署不成功。

### ISSUE THREAD

**Issue by xiaoxlm** [SwanHubX/self-hosted#6]
# 描述
安装[官网文档](https://docs.swanlab.cn/guide_cloud/self_host/docker-deploy.html)的操作。访问页面的如下:

<img width="1372" alt="Image" src="https://github.com/user-attachments/assets/57fa489e-339e-4163-aae7-16eeeaf47dde" />

## 查看swanlab-next 容器日志
```
[root@node2 ~]# docker logs swanlab-next
  ▲ Next.js 14.2.21
  - Local:        http://localhost:3000
  - Network:      http://0.0.0.0:3000

 ✓ Starting...
 ✓ Ready in 331ms
 ⚠ Umami is disabled because UMAMI_ID is not set
Failed to proxy http://traefik/api/pre_login Error: socket hang up
    at Socket.socketCloseListener (node:_http_client:484:27)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'ECONNRESET'
}
Error: socket hang up
    at Socket.socketCloseListener (node:_http_client:484:27)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'ECONNRESET'
}
 ⚠ Umami is disabled because UMAMI_ID is not set
Failed to proxy http://traefik/api/pre_login Error: socket hang up
    at Socket.socketCloseListener (node:_http_client:484:27)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'ECONNRESET'
}
Error: socket hang up
    at Socket.socketCloseListener (node:_http_client:484:27)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'ECONNRESET'
}
Failed to proxy http://traefik/api/pre_login Error: socket hang up
    at Socket.socketCloseListener (node:_http_client:484:27)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'ECONNRESET'
}
Error: socket hang up
    at Socket.socketCloseListener (node:_http_client:484:27)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'ECONNRESET'
}
Failed to proxy http://traefik/api/pre_login Error: socket hang up
    at Socket.socketCloseListener (node:_http_client:484:27)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'ECONNRESET'
}
Error: socket hang up
    at Socket.socketCloseListener (node:_http_client:484:27)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'ECONNRESET'
}
```

## 查看swanlab-traefik容器日志
```
[root@node2 ~]#docker logs --tail 500 swanlab-traefik
172.21.0.11 - - [03/Apr/2025:08:18:21 +0000] "GET /api/pre_login HTTP/1.1" 499 21 "-" "-" 53973 "swanlab-next@docker" "http://172.21.0.11:3000" 810ms
172.21.0.11 - - [03/Apr/2025:08:18:21 +0000] "GET /api/pre_login HTTP/1.1" 499 21 "-" "-" 53974 "swanlab-next@docker" "http://172.21.0.11:3000" 809ms
172.21.0.11 - - [03/Apr/2025:08:18:21 +0000] "GET /api/pre_login HTTP/1.1" 499 21 "-" "-" 53975 "swanlab-next@docker" "http://172.21.0.11:3000" 808ms
172.21.0.11 - - [03/Apr/2025:08:18:21 +0000] "GET /api/pre_login HTTP/1.1" 499 21 "-" "-" 53976 "swanlab-next@docker" "http://172.21.0.11:3000" 806ms
172.21.0.11 - - [03/Apr/2025:08:18:21 +0000] "GET /api/pre_login HTTP/1.1" 499 21 "-" "-" 53977 "swanlab-next@docker" "http://172.21.0.11:3000" 804ms
172.21.0.11 - - [03/Apr/2025:08:18:21 +0000] "GET /api/pre_login HTTP/1.1" 499 21 "-" "-" 53978 "swanlab-next@docker" "http://172.21.0.11:3000" 802ms
172.21.0.11 - - [03/Apr/2025:08:18:21 +0000] "GET /api/pre_login HTTP/1.1" 499 21 "-" "-" 53979 "swanlab-next@docker" "http://172.21.0.11:3000" 801ms
172.21.0.11 - - [03/Apr/2025:08:18:21 +0000] "GET /api/pre_login HTTP/1.1" 499 21 "-" "-" 53980 "swanlab-next@docker" "http://172.21.0.11:3000" 800ms
172.21.0.11 - - [03/Apr/2025:08:18:21 +0000] "GET /api/pre_login HTTP/1.1" 499 21 "-" "-" 53981 "swanlab-next@docker" "http://172.21.0.11:3000" 798ms
172.21.0.11 - - [03/Apr/2025:08:18:21 +0000] "GET /api/pre_login HTTP/1.1" 499 21 "-" "-" 53982 "swanlab-next@docker" "http://172.21.0.11:3000" 796ms
172.21.0.11 - - [03/Apr/2025:08:18:21 +0000] "GET /api/pre_login HTTP/1.1" 499 21 "-" "-" 53983 "swanlab-next@docker" "http://172.21.0.11:3000" 795ms
172.21.0.11 - - [03/Apr/2025:08:18:21 +0000] "GET /api/pre_login HTTP/1.1" 499 21 "-" "-" 53984 "swanlab-next@docker" "http://172.21.0.11:3000" 793ms
172.21.0.11 - - [03/Apr/2025:08:18:21 +0000] "GET /api/pre_login HTTP/1.1" 499 21 "-" "-" 53985 "swanlab-next@docker" "http://172.21.0.11:3000" 791ms
172.21.0.11 - - [03/Apr/2025:08:18:21 +0000] "GET /api/pre_login HTTP/1.1" 499 21 "-" "-" 53986 "swanlab-next@docker" "http://172.21.0.11:3000" 789ms
172.21.0.11 - - [03/Apr/2025:08:18:21 +0000] "GET /api/pre_login HTTP/1.1" 499 21 "-" "-" 53987 "swanlab-next@docker" "http://172.21.0.11:3000" 788ms
172.21.0.11 - - [03/Apr/2025:08:18:21 +0000] "GET /api/pre_login HTTP/1.1" 499 21 "-" "-" 53988 "swanlab-next@docker" "http://172.21.0.11:3000" 786ms
172.21.0.11 - - [03/Apr/2025:08:18:21 +0000] "GET /api/pre_login HTTP/1.1" 499 21 "-" "-" 53989 "swanlab-next@docker" "http://172.21.0.11:3000" 785ms
172.21.0.11 - - [03/Apr/2025:08:18:21 +0000] "GET /api/pre_login HTTP/1.1" 499 21 "-" "-" 53990 "swanlab-next@docker" "http://172.21.0.11:3000" 783ms
172.21.0.11 - - [03/Apr/2025:08:18:21 +0000] "GET /api/pre_login HTTP/1.1" 499 21 "-" "-" 53991 "swanlab-next@docker" "http://172.21.0.11:3000" 781ms
172.21.0.11 - - [03/Apr/2025:08:18:21 +0000] "GET /api/pre_login HTTP/1.1" 499 21 "-" "-" 53992 "swanlab-next@docker" "http://172.21.0.11:3000" 779ms
172.21.0.11 - - [03/Apr/2025:08:18:21 +0000] "GET /api/pre_login HTTP/1.1" 499 21 "-" "-" 53993 "swanlab-next@docker" "http://172.21.0.11:3000" 772ms
172.21.0.11 - - [03/Apr/2025:08:18:21 +0000] "GET /api/pre_login HTTP/1.1" 499 21 "-" "-" 53994 "swanlab-next@docker" "http://172.21.0.11:3000" 770ms
172.21.0.11 - - [03/Apr/2025:08:18:21 +0000] "GET /api/pre_login HTTP/1.1" 499 21 "-" "-" 53995 "swanlab-next@docker" "http://172.21.0.11:3000" 769ms
172.21.0.11 - - [03/Apr/2025:08:18:21 +0000] "GET /api/pre_login HTTP/1.1" 499 21 "-" "-" 53996 "swanlab-next@docker" "http://172.21.0.11:3000" 767ms
172.21.0.11 - - [03/Apr/2025:08:18:21 +0000] "GET /api/pre_login HTTP/1.1" 499 21 "-" "-" 53997 "swanlab-next@docker" "http://172.21.0.11:3000" 766ms
...
```

以及涉及一些 k8s 的报错内容:
```
error="middleware \"preprocess@file\" does not exist" entryPointName=web routerName=swanlab-server@docker
2025-04-03T07:38:47Z ERR error="middleware \"minio-host@file\" does not exist" entryPointName=web routerName=minio1@docker
2025-04-03T07:38:47Z ERR error="middleware \"preprocess@file\" does not exist" entryPointName=web routerName=swanlab-house@docker
2025-04-03T07:38:48Z ERR error="service \"fluent-bit-docker\" error: unable to find the IP address for the container \"/swanlab-fluentbit\": the server is ignored" container=fluent-bit-docker-863074bf9c28b983d153a0458f2467e6d8104cb625adeb68f26390d9e640121c providerName=docker
2025-04-03T07:38:48Z ERR error="service \"k8s-config-reloader-prometheus-k8s-1-monitoring-e614f20c-fe9d-4309-8781-50a77a18aafb-0\" error: unable to find the IP address for the container \"/k8s_config-reloader_prometheus-k8s-1_monitoring_e614f20c-fe9d-4309-8781-50a77a18aafb_0\": the server is ignored" container=k8s-config-reloader-prometheus-k8s-1-monitoring-e614f20c-fe9d-4309-8781-50a77a18aafb-0-cf3312a82c63575eb075df1026a8d4510f6e1fbc925a1fda4bec03fcb49a6f31 providerName=docker
2025-04-03T07:38:48Z ERR error="service \"k8s-prometheus-prometheus-k8s-1-monitoring-e614f20c-fe9d-4309-8781-50a77a18aafb-0\" error: unable to find the IP address for the container \"/k8s_prometheus_prometheus-k8s-1_monitoring_e614f20c-fe9d-4309-8781-50a77a18aafb_0\": the server is ignored" container=k8s-prometheus-prometheus-k8s-1-monitoring-e614f20c-fe9d-4309-8781-50a77a18aafb-0-1b5193d8dc0a64c4d07c35e8314adc19c03fdf789f013b28d861e52e802ccb99 providerName=docker
2025-04-03T07:38:48Z ERR error="service \"k8s-POD-prometheus-k8s-1-monitoring-e614f20c-fe9d-4309-8781-50a77a18aafb-0\" error: unable to find the IP address for the container \"/k8s_POD_prometheus-k8s-1_monitoring_e614f20c-fe9d-4309-8781-50a77a18aafb_0\": the server is ignored" container=k8s-POD-prometheus-k8s-1-monitoring-e614f20c-fe9d-4309-8781-50a77a18aafb-0-45e55cb37606dc1f26254fc4debdea41c302460e4362d6ae8475a8a49b2d964b providerName=docker
2025-04-03T07:38:48Z ERR error="service \"node-exporter-exporter\" error: port is missing" container=node-exporter-exporter-c164d23308bc395496d3ffb9aa7169ea7efa34b440ad9aeaf2c7c44ed84980d4 providerName=docker
2025-04-03T07:38:48Z ERR error="service \"unsloth\" error: port is missing" container=unsloth-22aebd52ae659505c6ad916df6245ad03cc3a6edbdbe802a26a1697b73008889 providerName=docker
2025-04-03T07:38:48Z ERR error="service \"k8s-nvidia-operator-validator-nvidia-operator-validator-fsf49-gpu-operator-8f43daea-8a2d-4435-b99b-d7a546b4dfdd-2\" error: unable to find the IP address for the container \"/k8s_nvidia-operator-validator_nvidia-operator-validator-fsf49_gpu-operator_8f43daea-8a2d-4435-b99b-d7a546b4dfdd_2\": the server is ignored" container=k8s-nvidia-operator-validator-nvidia-operator-validator-fsf49-gpu-operator-8f43daea-8a2d-4435-b99b-d7a546b4dfdd-2-9d16496171fc299563221c9b382e73e53b1d0f41b39c70a04928678ad4bf4a8d providerName=docker
...
```

# 环境
OS: Ubuntu 22.04.4 LTS
docker 版本:
```
# docker version
Client:
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.21.1
 Git commit:        24.0.7-0ubuntu2~22.04.1
 Built:             Wed Mar 13 20:23:54 2024
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.21.1
  Git commit:       24.0.7-0ubuntu2~22.04.1
  Built:            Wed Mar 13 20:23:54 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.12
  GitCommit:
 nvidia:
  Version:          1.1.12-0ubuntu2~22.04.1
  GitCommit:        a5a5833c14a15fd9c86bcece85d5ec6621b65652
 docker-init:
  Version:          0.19.0
  GitCommit:
```

执行的 docker-compose.yml 内容:
```
networks:
  swanlab-net:
    name: swanlab-net

volumes:
  swanlab-house:
    name: swanlab-house
  fluent-bit:
    name: fluent-bit

x-common: &common
  networks:
    - swanlab-net
  restart: unless-stopped
  logging:
    options:
      max-size: 50m
      max-file: "3"

services:
  # Gateway
  traefik:
    <<: *common
    image: ccr.ccs.tencentyun.com/self-hosted/traefik:v3.0
    container_name: swanlab-traefik
    ports:
      - "8000:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "0.0.0.0:8080/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
  # Databases
  postgres:
    <<: *common
    image: ccr.ccs.tencentyun.com/self-hosted/postgres:16.1
    container_name: swanlab-postgres
    environment:
      TZ: UTC
      POSTGRES_USER: swanlab
      POSTGRES_PASSWORD: xxxx # 屏蔽内容
      POSTGRES_DB: app
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    <<: *common
    image: ccr.ccs.tencentyun.com/self-hosted/redis-stack-server:7.2.0-v15
    container_name: swanlab-redis
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
  clickhouse:
    <<: *common
    image: ccr.ccs.tencentyun.com/self-hosted/clickhouse:24.3
    container_name: swanlab-clickhouse
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse/
    environment:
      TZ: UTC
      CLICKHOUSE_USER: swanlab
      CLICKHOUSE_PASSWORD: xxxx # 屏蔽内容
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "0.0.0.0:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
  logrotate:
    <<: *common
    image: ccr.ccs.tencentyun.com/self-hosted/logrotate:v1
    container_name: swanlab-logrotate
    volumes:
      - swanlab-house:/data
    environment:
      LOGS_DIRECTORIES: "/data"
      LOGROTATE_COPIES: 25
      LOGROTATE_SIZE: "25M"
      LOGROTATE_CRONSCHEDULE: "*/20 * * * * *"
      LOGROTATE_INTERVAL: daily
    labels:
      - "traefik.enable=false"
  fluent-bit:
    <<: *common
    image: ccr.ccs.tencentyun.com/self-hosted/fluent-bit:3.0
    container_name: swanlab-fluentbit
    command: ["fluent-bit/bin/fluent-bit", "-c", "/conf/fluent-bit.conf"]
    volumes:
      - fluent-bit:/data
      - swanlab-house:/metrics
    environment:
      LOG_PATH: /metrics/*.log
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 8123
      CLICKHOUSE_USER: swanlab
      CLICKHOUSE_PASS: xxxx # 屏蔽内容
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
  minio:
    <<: *common
    image: ccr.ccs.tencentyun.com/self-hosted/minio:RELEASE.2025-02-28T09-55-16Z
    container_name: swanlab-minio
    volumes:
      - ./data/minio:/data
    environment:
      MINIO_ROOT_USER: swanlab
      MINIO_ROOT_PASSWORD: c709XMwroh
    labels:
      - "traefik.http.services.minio.loadbalancer.server.port=9000"
      - "traefik.http.routers.minio1.rule=PathPrefix(`/swanlab-public`)"
      - "traefik.http.routers.minio1.middlewares=minio-host@file"
      - "traefik.http.routers.minio2.rule=PathPrefix(`/swanlab-private`)"
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 3
  # swanlab services
  swanlab-server:
    <<: *common
    image: ccr.ccs.tencentyun.com/self-hosted/swanlab-server:v1
    container_name: swanlab-server
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://swanlab:ks3KJiqhKX@postgres:5432/app?schema=public
      - REDIS_URL=redis://default@redis:6379
      - SERVER_PREFIX=/api
      - ACCESS_KEY=swanlab
      - SECRET_KEY=xxxx # 屏蔽内容
    labels:
      - "traefik.http.routers.swanlab-server.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.swanlab-server.middlewares=preprocess@file"
    command: bash -c "npx prisma migrate deploy && pm2-runtime app.js"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "0.0.0.0:3000/api/"]
      interval: 10s
      timeout: 5s
      retries: 3
  swanlab-house:
    <<: *common
    image: ccr.ccs.tencentyun.com/self-hosted/swanlab-house:v1
    container_name: swanlab-house
    depends_on:
      clickhouse:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - SH_API_PREFIX=/api/house
      - SH_LOG_PATH=/data/metrics.log
      - SH_DATABASE_URL=tcp://swanlab:73MvBT6pBf@clickhouse:9000/app
      - SH_SERVER_URL=http://swanlab-server:3000/api
      - SH_MINIO_SECRET_ID=swanlab
      - SH_MINIO_SECRET_KEY=xxxx # 屏蔽内容
    labels:
      - "traefik.http.routers.swanlab-house.rule=PathPrefix(`/api/house`) || PathPrefix(`/api/internal`)"
      - "traefik.http.routers.swanlab-house.middlewares=preprocess@file"
    volumes:
      - swanlab-house:/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "0.0.0.0:3000/api/house/health"]
      interval: 10s
      timeout: 5s
      retries: 3
  swanlab-cloud:
    <<: *common
    image: ccr.ccs.tencentyun.com/self-hosted/swanlab-cloud:v1
    container_name: swanlab-cloud
    depends_on:
      swanlab-server:
        condition: service_healthy
  swanlab-next:
    <<: *common
    image: ccr.ccs.tencentyun.com/self-hosted/swanlab-next:v1
    container_name: swanlab-next
    depends_on:
      swanlab-server:
        condition: service_healthy
    environment:
      - NEXT_CLOUD_URL=http://swanlab-cloud:80
    labels:
      - "traefik.http.routers.swanlab-next.rule=PathPrefix(`/`)"
```

这是本次测试中还发现的另一个 issue:  [swanlab-fluentbit 容器中报错](https://github.com/SwanHubX/self-hosted/issues/5)
